export { default as About } from './about'
export { default as Gallery } from './gallery'
export { default as Shop } from './shop'
export { default as Cart } from './cart'
export { default as Products } from './products'
export { default as ShoppingCart } from './shopping-cart'
export { default as CartSummary } from './cart-summary'
export { default as Result } from './result'
export { default as ProductDetail } from './product-detail'
export * from './shared'
